name: Hello World
on: 
  push: 
    branches:
      - main
jobs:
  First-HelloWorld-Job:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello World GitHub Actions Testing"
